[tool.poetry]
name = "aw-watcher-afk"
version = "0.2.0"
description = ""
authors = ["Erik Bjäreholt <erik@bjareho.lt>"]
license = "MPL-2.0"

[tool.poetry.scripts]
aw-watcher-afk = "aw_watcher_afk:main"

[tool.poetry.dependencies]
python = "^3.7"
aw-client = {git = "https://github.com/ActivityWatch/aw-client.git"}
pyobjc-framework-Quartz = { version = "^6.1", platform = "darwin" }
python-xlib = { version = "^0.28", platform = "linux" }
pyuserinput = {git = "https://github.com/PyUserInput/PyUserInput.git", platform = "linux", rev = "ac2d4c7a7f4b1a72e70b1a2ef8925d5312fb12bc"}
pypiwin32 = {version = "^223", platform = "win32"}
pyhook = {url = "https://github.com/ActivityWatch/wheels/raw/master/pyHook-1.5.1-cp37-cp37m-win_amd64.whl", platform = "win32" }

[tool.poetry.dev-dependencies]
mypy = "^0.761"
macholib = {version = "^1.13", platform = "darwin"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
