[tool.poetry]
name = "aw-qt"
version = "0.1.0"
description = "Trayicon for ActivityWatch"
authors = ["Erik Bjäreholt <erik@bjareho.lt>"]
license = "MPL-2.0"
include = ["aw_qt/resources.py"]  # resources.py is in .gitignore and generated before build
packages = [
    { include = "aw_qt" },
]

[tool.poetry.scripts]
aw-qt = "aw_qt:main"

[tool.poetry.dependencies]
python = "^3.6, <3.8"
aw-core = {git = "https://github.com/ActivityWatch/aw-core.git"}
PyQt5 = "5.10.1"
sip = "4.19.8"
pyobjc = { version = "^6.1", platform = "darwin" }
click = "^7.1.2"

[tool.poetry.dev-dependencies]
mypy = "^0.761"
PyQt5-stubs = "~5.13"  # Should ideally be ~5.10, but no such version exists
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
